# Terminal
=======
python-cjson
libabiword                                                                     
                                                                               
# Browse                                                                       
gnash-plugin                                                                   
totem-mozplugin                                                                

# Terminal                                                                     
vte                                                                            
